/*
 * app_config.h
 *
 *  Created on: 12 Jul 2024
 *      Author: Maldus
 */

#ifndef SERVICES_APP_CONFIG_H_
#define SERVICES_APP_CONFIG_H_


#define APP_CONFIG_DEVICE_MODEL 0

#define APP_CONFIG_FIRMWARE_VERSION_MAJOR 0
#define APP_CONFIG_FIRMWARE_VERSION_MINOR 0
#define APP_CONFIG_FIRMWARE_VERSION_PATCH 1


#endif /* SERVICES_APP_CONFIG_H_ */
