/*
 * app_config.h
 *
 *  Created on: 6 Aug 2024
 *      Author: Maldo
 */

#ifndef CONFIG_APP_CONFIG_H_
#define CONFIG_APP_CONFIG_H_

#define APP_CONFIG_DEVICE_MODEL 0

#define APP_CONFIG_FIRMWARE_VERSION_MAJOR 0
#define APP_CONFIG_FIRMWARE_VERSION_MINOR 0
#define APP_CONFIG_FIRMWARE_VERSION_PATCH 1

#define APP_CONFIG_DEFAULT_PID_KP 0.5
#define APP_CONFIG_DEFAULT_PID_KI 0.1
#define APP_CONFIG_DEFAULT_PID_KD 0.0



#endif /* CONFIG_APP_CONFIG_H_ */
